clear all
close all hidden
clc

%Calculating hypergeometric distribution
% Relating the matlab variables to the variables that Tiffany used in
% lecture
% x = i (n?) overlap
% M = g whole sample
% K = f one circle
% N = c other circle

% Note: the numbers used in this script were taken from the venn
% diagrams generated by VennMaster

% proximal colon 
BT_GF_overlap = 110 + 192; % proteins in overlap between GF and B theta
all_prot = 843; % all proteins identified in the study
GF = 71 + 29 + 110 + 192; % all proteins in GF
BT = 15 + 52 + 192 + 110; % all proteins in B theta
BT_GF = hygepdf(BT_GF_overlap,all_prot,GF,BT)

BT_conv_overlap = 192 + 15; % proteins in overlap between conventional and B theta
conv = 53 + 29 + 15 + 192; % all proteins in conventional
BT_conv = hygepdf(BT_conv_overlap, all_prot, BT, conv)

GF_conv_overlap = 29 + 192; % proteins in overlap between GF and conventional 
GF_conv = hygepdf(GF_conv_overlap, all_prot, GF, conv)

%cecum 
BT_GF_overlap = 179 + 87;
GF = 97 + 42+ 179+ 87;
BT= 179+87+ 6+ 15;
BT_GF = hygepdf(BT_GF_overlap,all_prot,GF,BT)

BT_conv_overlap = 179 + 6;
conv = 56 + 42 + 6 + 179;
BT_conv = hygepdf(BT_conv_overlap, all_prot, BT, conv)

GF_conv_overlap =42 + 179;
GF_conv = hygepdf(GF_conv_overlap, all_prot, GF, conv)

%stomach
BT_GF_overlap =168+21;
BT_conv_coverlap = 168+19;
GF_conv_overlap = 168 + 87;
GF = 90+21+168+87;
BT = 168+19+21+11;
conv = 144 + 87 + 168 + 19;
BT_GF = hygepdf(BT_GF_overlap,all_prot,GF,BT)
BT_conv = hygepdf(BT_conv_overlap, all_prot, BT, conv)
GF_conv = hygepdf(GF_conv_overlap, all_prot, GF, conv)


%ileum
BT_GF_overlap = 209 + 214;
BT_conv_coverlap = 214 + 11;
GF_conv_overlap = 26 + 214;
GF = 119 + 26+ 209 + 214;
BT =42 + 11 + 214 + 209;
conv = 57 + 11 + 26+ 214;
BT_GF = hygepdf(BT_GF_overlap,all_prot,GF,BT)
BT_conv = hygepdf(BT_conv_overlap, all_prot, BT, conv)
GF_conv = hygepdf(GF_conv_overlap, all_prot, GF, conv)

%jejunum
BT_GF_overlap = 219 + 49;
BT_conv_coverlap = 219 + 34;
GF_conv_overlap = 10 + 219;
GF = 12 + 10 + 219 + 49;
BT = 49 + 90 + 219 + 34;
conv = 10 + 219 + 34 + 66;
BT_GF = hygepdf(BT_GF_overlap,all_prot,GF,BT)
BT_conv = hygepdf(BT_conv_overlap, all_prot, BT, conv)
GF_conv = hygepdf(GF_conv_overlap, all_prot, GF, conv)


